### ISSUE TITLE
Imhotep Error Messages reference indeed internal wiki

### ISSUE THREAD

**Issue by youknowjack** [indeedeng/iql#11]
From imhotep created by [ThomasBergman1](https://github.com/ThomasBergman1) : indeedeng/imhotep#16  

I saw an error like this when doing a particularly heavy query.

Query failed: 
Looks like the IQL server got overloaded and is restarting. 
Please take a look at your query and consider if it is too heavy. 
Wiki: 
https://wiki.indeed.com/display/INTEL/_Performance+Considerations+for+IQL+usage

**Comment by hnarasaki** [comment]
Should this issue be closed?
