### ISSUE TITLE
New datasets are not added to "from" dropdown

### ISSUE THREAD

**Issue by jx-opher** [indeedeng/iql#8]
Creating new indexes does not populate the index selector control (the "from" input).

To reproduce:
* In IUploader, create a new dataset -- fooindextest
* Upload a simple TSV, the [single-day NASA weblog](http://indeedeng.github.io/imhotep/files/nasa_19950801.tsv) for example
* Refresh the page around every 30 seconds until the UI indicates the TSV has been indexed
* In IQL, click the "from" input...

[Documentation indicates](http://opensource.indeedeng.io/imhotep/docs/quick-start/#uploading-a-data-file) you should "Allow a minute or two for your dataset to be available in the IQL web client.", but the dataset will never show up in the dropdown.

If you open an incognito window and navigate to the IQL webapp, you _will_ see the dataset listed as an option.

It appears like the local storage value for {{iql_prod_getDatasets__cache}} never gets refreshed, even after hard reloads.

**Comment by youknowjack** [comment]
As a workaround, you should be able to manually clear the local storage cache by selecting the "Clear Cache" menu item from the "More" dropdown.
