### ISSUE TITLE
Document field description capability via suggestions.xml

### ISSUE THREAD

**Issue by youknowjack** [indeedeng/iql#9]
Need to incorporate how to provide field documentation to IQL webapp.

The current way (until we open source our metadata service) to set descriptions is to put it in a directory on the machine that runs IQL. The directory is set with ramses.metadata.dir config property and is typically /var/data/iql/ramses_metdata/.

Each index to be described has to have a subdirectory under that path with name matching the index name. The descriptions will go in a file called suggestions.xml under that subdirectory. Example:
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE beans PUBLIC "-//SPRING//DTD BEAN 2.0//EN" "http://www.springframework.org/dtd/spring-beans-2.0.dtd">

<beans default-lazy-init="true">
    <bean id="suggestionMap" class="java.util.HashMap">
        <constructor-arg>
            <map>
                <entry key="imhotepFieldName" value="This describes what is in the field" />
                <entry key="imhotepAnotherFieldName" value="This describes what is in another field" />
            </map>
        </constructor-arg>
    </bean>
</beans>
```

The descriptions need to be put as <entry/> lines. The rest of the file will stay the same. 

Other examples (for our public Imhotep datasets) are in the attached zip file.

[suggestions.zip](https://github.com/indeedeng/iql/files/1820418/suggestions.zip)

**Comment by ThomasBergman1** [comment]
Great success!
Have verified that this works.
Thanks
